import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
const t = new StdioClientTransport({ command: 'node', args: ['dist/cli.js'], stderr: 'inherit' });
const c = new Client({ name: 'probe', version: '0' });
await c.connect(t);
const tools = await c.listTools();
console.log('tools:', tools.tools.map(x => x.name).join(' '));
const s = await c.callTool({ name: 'diorama_status', arguments: {} });
console.log('status:', s.content[0].text.slice(0, 200));
const g = await c.callTool({ name: 'diorama_inspect_page', arguments: {} });
console.log('inspect (no ext):', g.isError, g.content[0].text.slice(0, 120));
await c.close(); process.exit(0);
